// This file is auto-generated from material_colors.json
use phf::phf_map;
use crate::block::Block;
use lodestone_common::types::color::Color;

#[derive(Debug, Clone, Copy, Eq, PartialEq, Hash)]
pub enum Material {
    Clay,
    ColorBlack,
    ColorBlue,
    ColorBrown,
    ColorCyan,
    ColorGray,
    ColorGreen,
    ColorLightBlue,
    ColorLightGray,
    ColorLightGreen,
    ColorMagenta,
    ColorOrange,
    ColorPink,
    ColorPurple,
    ColorRed,
    ColorYellow,
    CrimsonHyphae,
    CrimsonNylium,
    CrimsonStem,
    Deepslate,
    Diamond,
    Dirt,
    Emerald,
    Fire,
    GlowLichen,
    Gold,
    Grass,
    Ice,
    Lapis,
    Metal,
    Nether,
    None,
    Plant,
    Podzol,
    Quartz,
    RawIron,
    Sand,
    Snow,
    Stone,
    TerracottaBlack,
    TerracottaBlue,
    TerracottaBrown,
    TerracottaCyan,
    TerracottaGray,
    TerracottaGreen,
    TerracottaLightBlue,
    TerracottaLightGray,
    TerracottaLightGreen,
    TerracottaMagenta,
    TerracottaOrange,
    TerracottaPink,
    TerracottaPurple,
    TerracottaRed,
    TerracottaWhite,
    TerracottaYellow,
    WarpedHyphae,
    WarpedNylium,
    WarpedStem,
    WarpedWartBlock,
    Water,
    Wood,
    Wool,
}

impl Material {
    pub fn get_color(&self) -> Color {
        match self {
            Material::Clay => Color { r: 164, g: 168, b: 184, a: 255 },
            Material::ColorBlack => Color { r: 25, g: 25, b: 25, a: 255 },
            Material::ColorBlue => Color { r: 51, g: 76, b: 178, a: 255 },
            Material::ColorBrown => Color { r: 102, g: 76, b: 51, a: 255 },
            Material::ColorCyan => Color { r: 76, g: 127, b: 153, a: 255 },
            Material::ColorGray => Color { r: 76, g: 76, b: 76, a: 255 },
            Material::ColorGreen => Color { r: 102, g: 127, b: 51, a: 255 },
            Material::ColorLightBlue => Color { r: 102, g: 153, b: 216, a: 255 },
            Material::ColorLightGray => Color { r: 153, g: 153, b: 153, a: 255 },
            Material::ColorLightGreen => Color { r: 127, g: 204, b: 25, a: 255 },
            Material::ColorMagenta => Color { r: 178, g: 76, b: 216, a: 255 },
            Material::ColorOrange => Color { r: 216, g: 127, b: 51, a: 255 },
            Material::ColorPink => Color { r: 242, g: 127, b: 165, a: 255 },
            Material::ColorPurple => Color { r: 127, g: 63, b: 178, a: 255 },
            Material::ColorRed => Color { r: 153, g: 51, b: 51, a: 255 },
            Material::ColorYellow => Color { r: 229, g: 229, b: 51, a: 255 },
            Material::CrimsonHyphae => Color { r: 92, g: 25, b: 29, a: 255 },
            Material::CrimsonNylium => Color { r: 189, g: 48, b: 49, a: 255 },
            Material::CrimsonStem => Color { r: 148, g: 63, b: 97, a: 255 },
            Material::Deepslate => Color { r: 100, g: 100, b: 100, a: 255 },
            Material::Diamond => Color { r: 92, g: 219, b: 213, a: 255 },
            Material::Dirt => Color { r: 151, g: 109, b: 77, a: 255 },
            Material::Emerald => Color { r: 0, g: 217, b: 58, a: 255 },
            Material::Fire => Color { r: 255, g: 0, b: 0, a: 255 },
            Material::GlowLichen => Color { r: 127, g: 167, b: 150, a: 255 },
            Material::Gold => Color { r: 250, g: 238, b: 77, a: 255 },
            Material::Grass => Color { r: 127, g: 178, b: 56, a: 255 },
            Material::Ice => Color { r: 160, g: 160, b: 255, a: 255 },
            Material::Lapis => Color { r: 74, g: 128, b: 255, a: 255 },
            Material::Metal => Color { r: 167, g: 167, b: 167, a: 255 },
            Material::Nether => Color { r: 112, g: 2, b: 0, a: 255 },
            Material::None => Color { r: 0, g: 0, b: 0, a: 0 },
            Material::Plant => Color { r: 0, g: 124, b: 0, a: 255 },
            Material::Podzol => Color { r: 129, g: 86, b: 49, a: 255 },
            Material::Quartz => Color { r: 255, g: 252, b: 245, a: 255 },
            Material::RawIron => Color { r: 216, g: 175, b: 147, a: 255 },
            Material::Sand => Color { r: 247, g: 233, b: 163, a: 255 },
            Material::Snow => Color { r: 255, g: 255, b: 255, a: 255 },
            Material::Stone => Color { r: 112, g: 112, b: 112, a: 255 },
            Material::TerracottaBlack => Color { r: 37, g: 22, b: 16, a: 255 },
            Material::TerracottaBlue => Color { r: 76, g: 62, b: 92, a: 255 },
            Material::TerracottaBrown => Color { r: 76, g: 50, b: 35, a: 255 },
            Material::TerracottaCyan => Color { r: 87, g: 92, b: 92, a: 255 },
            Material::TerracottaGray => Color { r: 57, g: 41, b: 35, a: 255 },
            Material::TerracottaGreen => Color { r: 76, g: 82, b: 42, a: 255 },
            Material::TerracottaLightBlue => Color { r: 112, g: 108, b: 138, a: 255 },
            Material::TerracottaLightGray => Color { r: 135, g: 107, b: 98, a: 255 },
            Material::TerracottaLightGreen => Color { r: 103, g: 117, b: 53, a: 255 },
            Material::TerracottaMagenta => Color { r: 149, g: 87, b: 108, a: 255 },
            Material::TerracottaOrange => Color { r: 159, g: 82, b: 36, a: 255 },
            Material::TerracottaPink => Color { r: 160, g: 77, b: 78, a: 255 },
            Material::TerracottaPurple => Color { r: 122, g: 73, b: 88, a: 255 },
            Material::TerracottaRed => Color { r: 142, g: 60, b: 46, a: 255 },
            Material::TerracottaWhite => Color { r: 209, g: 177, b: 161, a: 255 },
            Material::TerracottaYellow => Color { r: 186, g: 133, b: 36, a: 255 },
            Material::WarpedHyphae => Color { r: 86, g: 44, b: 62, a: 255 },
            Material::WarpedNylium => Color { r: 22, g: 126, b: 134, a: 255 },
            Material::WarpedStem => Color { r: 58, g: 142, b: 140, a: 255 },
            Material::WarpedWartBlock => Color { r: 20, g: 180, b: 133, a: 255 },
            Material::Water => Color { r: 64, g: 64, b: 255, a: 255 },
            Material::Wood => Color { r: 143, g: 119, b: 72, a: 255 },
            Material::Wool => Color { r: 199, g: 199, b: 199, a: 255 },
        }
    }

    pub fn get_material_from_block(block: &Block) -> Material {
        match block {
            Block::Air => Material::None,
            Block::Stone => Material::Stone,
            Block::Granite => Material::Dirt,
            Block::Grass => Material::Grass,
            Block::Dirt => Material::Dirt,
            Block::Cobblestone => Material::Stone,
            Block::OakPlanks => Material::Wood,
            Block::OakSapling => Material::Plant,
            Block::Bedrock => Material::Stone,
            Block::FlowingWater => Material::Water,
            _ => Material::None,
        }
    }
}